// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdstUL1MHAqNs_17RsIu9B2hNvh0dTRk',
    appId: '1:281153906087:web:e5287a434465f2c3574282',
    messagingSenderId: '281153906087',
    projectId: 'fire-fotines',
    authDomain: 'fire-fotines.firebaseapp.com',
    storageBucket: 'fire-fotines.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdIj7J-a4_zvsips1foCeqP3WhCIXP0M',
    appId: '1:281153906087:android:38aed10b5da19a54574282',
    messagingSenderId: '281153906087',
    projectId: 'fire-fotines',
    storageBucket: 'fire-fotines.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDj4QGbIEpsSHj24pQreoUmknujj8k14',
    appId: '1:281153906087:ios:8a94b3c940178ffc574282',
    messagingSenderId: '281153906087',
    projectId: 'fire-fotines',
    storageBucket: 'fire-fotines.appspot.com',
    iosBundleId: 'com.example.fotin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDj4QGbIEpsSHj24pQreoUmknujj8k14',
    appId: '1:281153906087:ios:454ac7148ac4e78a574282',
    messagingSenderId: '281153906087',
    projectId: 'fire-fotines',
    storageBucket: 'fire-fotines.appspot.com',
    iosBundleId: 'com.example.fotin.RunnerTests',
  );
}
